config/routes.rb
Rails.application.routes.draw do
  # Place non-resourceful routes above resourceful ones
  get '/countries/data', to: 'countries#data'

  resources :countries do
    collection do
      patch :update_ranks
    end
    member do
      patch :toggle_been
    end
  end

  # Define other routes here
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :price, presence: true, numericality: true
  validates :published_date, presence: true
end

app/models/country.rb
# app/models/country.rb
class Country < ApplicationRecord
    # Add validations as needed, for example:
    validates :been, inclusion: { in: [true, false] }
    validates :notes, length: { maximum: 500 }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :published_date)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.order(:rank)
  end
  
  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_ranks
    ActiveRecord::Base.transaction do
      params[:country_ids].each_with_index do |id, index|
        country = Country.find(id)
        country.update(rank: index + 1)
      end
    end
    head :ok
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def toggle_been
    country = Country.find(params[:id])
    country.update(been: params[:been])
  
    respond_to do |format|
      format.json { head :no_content }
    end
  end
  def data
    countries = Country.all
    render json: countries.map { |c| { code: c.code, been: c.been } } # Adjust the mapping as per your model
  end

  def your_action_name
    @visited_countries_count = Country.where(been: true).count
    # Other necessary code...
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, :rank, :been, :code, :notes)  
    end


     

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
    <strong>Author:</strong>
    <%= book.author %>
    <strong>Price:</strong>
    <%= book.price %>
    <strong>Publish Date:</strong>
    <%= book.published_date %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
    <%= form.label :published_date, style: "display: block" %>
    <%= form.text_field :published_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= country.rank %>
  </p>

</div>

app/views/countries/_country_item.html.erb
<!-- app/views/countries/_country_item.html.erb -->
<li class="country-item" data-id="<%= country.id %>">
  <%= "#{country.rank}. #{country.name}" %>
   
  <%= check_box_tag "been_#{country.id}", "been", country.been, class: "country-been-checkbox", data: { id: country.id } %>
  
  <!-- Link to Edit instead of Show -->
  <%= link_to 'Edit', edit_country_path(country), class: 'edit-country-btn' %>
</li>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rank, style: "display: block" %>
    <%= form.number_field :rank %>
  </div>

  <!-- New section for notes -->
  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes, rows: 5 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<!-- app/views/countries/index.html.erb -->
<!-- Basic Navbar Structure -->
<nav class="navbar"> 
<h1>Morgan And Tyler's Travel</h2>
</nav>

<div class="countries-container">
  <div class="countries-not-visited">
    <h3>Not Visited (Rank Here)</h3>
    <ul id="countries-not-visited-list" class="sortable-list">
      <% @countries.where(been: false).order(:rank).each do |country| %>
        <%= render 'country_item', country: country %>
      <% end %>
    </ul>
  </div>

  <div class="countries-visited">
    <h3>Visited</h3>
    <ul id="countries-visited-list" class="sortable-list">
      <% @countries.where(been: true).order(:rank).each do |country| %>
        <%= render 'country_item', country: country %>
      <% end %>
    </ul>
  </div>

  <div class="countries-map">
    <div class="map-title">
     <% visited_countries_count = @countries.where(been: true).count %> 


     <h2><%= visited_countries_count %>/191 Countries Visited</h2>
     <h2>We have visited <%= (visited_countries_count.to_f / 191 * 100).round(2) %>% of the world!</h2>
     
    </div>

    <div id="world-map" style="height: 500px; width: 100%;"></div>
    <button id="update-button">Update</button>

  </div>
</div>


<!-- Include SortableJS from a CDN -->
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/Sortable.min.js"></script>

 


<script>
  document.addEventListener('DOMContentLoaded', function() {
    var geoJsonLayer;

    // Function to update the map style
    function updateCountryStyle(countryCode, beenStatus) {
      if (geoJsonLayer) {
        geoJsonLayer.eachLayer(function(layer) {
          if (layer.feature.properties.su_a3 === countryCode) {
            var newColor = beenStatus ? 'green' : 'grey';
            layer.setStyle({ fillColor: newColor });
          }
        });
      }
    }

    // Initialize the map
    var map = L.map('world-map').setView([20, 0], 2);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      noWrap: true
 
    }).addTo(map); 
    map.setZoom(1); 

    // Fetch country data and initialize the map layer
    fetch('/countries/data.json')
      .then(function(response) {
        return response.json();
      })
      .then(function(countriesData) {
        fetch('/custom.geo.json') // Change to your actual geoJSON file path
          .then(function(response) {
            return response.json();
          })
          .then(function(geojsonData) {
            geoJsonLayer = L.geoJson(geojsonData, {
              style: function(feature) {
                var country = countriesData.find(c => c.code === feature.properties.su_a3);
                var color = country && country.been ? 'green' : 'grey';
                return { fillColor: color, weight: 1, opacity: 1, color: 'white', fillOpacity: 0.7 };
              }
            }).addTo(map);
          });
      });

    // Initialize sortable for both lists
    ['countries-not-visited-list', 'countries-visited-list'].forEach(function(listId) {
      var el = document.getElementById(listId);
      Sortable.create(el, {
        group: 'countries',
        onEnd: function(evt) {
          updateRanksForList(el);
        }
      });
    });

    var updateButton = document.getElementById('update-button');
   if (updateButton) {
    updateButton.addEventListener('click', function() {
      window.location.reload(); // Refresh the page
    });
   }    
    // Function to update ranks
    function updateRanksForList(list) {
      var countryIds = Array.from(list.children).map(function(item) {
        return item.getAttribute('data-id');
      });

      fetch('<%= update_ranks_countries_path %>', {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        },
        body: JSON.stringify({ country_ids: countryIds })
      });
    }

    // Checkbox change handler
    document.querySelectorAll('.country-been-checkbox').forEach(function(checkbox) {
      checkbox.addEventListener('change', function() {
        var countryId = this.dataset.id;
        var countryCode = this.dataset.code;
        var beenStatus = this.checked;

        fetch('/countries/' + countryId + '/toggle_been', {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
          },
          body: JSON.stringify({ been: beenStatus })
        }).then(function(response) {
          if (response.ok) {
            updateCountryStyle(countryCode, beenStatus);
            var targetListId = beenStatus ? 'countries-visited-list' : 'countries-not-visited-list';
            var targetList = document.getElementById(targetListId);
            var countryItem = document.querySelector('.country-item[data-id="' + countryId + '"]');
            targetList.appendChild(countryItem);

            updateRanksForList(document.getElementById('countries-not-visited-list'));
            updateRanksForList(document.getElementById('countries-visited-list'));
          }
        });
      });
    });
  });
</script>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<!-- Display the notes -->
<div class="country-notes">
  <strong>Notes:</strong>
  <p><%= @country.notes %></p>
</div>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  </body>
</html>